# permissions for end users to view tuffmongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tuffmongodb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-mongodb-operator
    app.kubernetes.io/part-of: kubernetes-mongodb-operator
    app.kubernetes.io/managed-by: kustomize
  name: tuffmongodb-viewer-role
rules:
- apiGroups:
  - app.1k.local
  resources:
  - tuffmongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.1k.local
  resources:
  - tuffmongodbs/status
  verbs:
  - get
