apiVersion: app.1k.local/v1alpha1
kind: TuffMongoDB
metadata:
  labels:
    app.kubernetes.io/name: tuffmongodb
    app.kubernetes.io/instance: tuffmongodb-sample
    app.kubernetes.io/part-of: kubernetes-mongodb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-mongodb-operator
  name: mongodb-tuff-1
spec:
  name: tuffmongo
  namespace: tuff
  component: mongodb
  image: image-registry.openshift-image-registry.svc:5000/tuff/busybox
  ports:
  - containerPort: 27017
    name: mongodbport
    protocol: TCP
  replicas: 1
  volumeMounts:
  - mountPath: /usr/mongo/data
    name: mongo-db-data
  volumes:
  - name: mongo-db-data
    volumeSource: pvc-mongo-db-data
